### ISSUE TITLE
Error thrown on tree expand

### ISSUE THREAD

**Issue by lokesh-couchbase** [couchbaselabs/couchbase_jetbrains_plugin#170]
Whenever I expand the tree, I get the following error

<img width="1511" alt="image" src="https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/113521973/bf429920-901e-40be-99cb-eab50c3c060a">

In Text: 
```
java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:216)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowForPath(DefaultTreeUI.java:766)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateLeadSelectionRow(BasicTreeUI.java:2847)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4409)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:616)
	at java.desktop/javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:400)
	at com.couchbase.intellij.database.DataLoader.lambda$listBuckets$0(DataLoader.java:92)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

This is making overall experience bad as when we click on tree, error thrown message is shown at the bottom right. However I couldn't find anything wrong with the functionality

**Comment by deniswsrosa** [comment]
Feature is now available in the 1.0.8 version
