### ISSUE TITLE
Support KV-Only Clusters

### ISSUE THREAD

**Issue by deniswsrosa** [couchbaselabs/couchbase_jetbrains_plugin#51]

**Comment by roikatz** [comment]
Just to have some context
when you are starting the plugin on a kv only cluster you are getting this warning message:
![image](https://github.com/couchbaselabs/couchbase_jetbrains_plugin/assets/9395306/4e7e7936-ffce-4136-9714-cd8a89f01f9b)

Also the Plugin throws "ServiceNotAvailableException" as the query service is missing.
full exception sample:
`com.couchbase.client.core.error.ServiceNotAvailableException: The query service is not available in the cluster. {"completed":true,"coreId":"0x70e49c6000000001","idempotent":false,"requestId":111,"requestType":"QueryRequest","retried":0,"service":{"bucket":"travel-sample","operationId":"null","scope":"tenant_agent_00","statement":"Select meta(couchbaseAlias).id as cbFileNameId, meta(couchbaseAlias).type as cbMetaType  from `users` as couchbaseAlias   order by meta(couchbaseAlias).id  limit 10","type":"query"},"timeoutMs":75000,"timings":{"totalMicros":82}}
	at com.couchbase.client.core.util.CoreAsyncUtils.block(CoreAsyncUtils.java:54)
	at com.couchbase.client.core.api.kv.CoreAsyncResponse.toBlocking(CoreAsyncResponse.java:53)
	at com.couchbase.client.core.api.query.CoreQueryOps.queryBlocking(CoreQueryOps.java:45)
	at com.couchbase.client.java.Scope.query(Scope.java:177)
	at com.couchbase.client.java.Scope.query(Scope.java:161)
	at com.couchbase.intellij.database.DataLoader.listDocuments(DataLoader.java:210)
	at com.couchbase.intellij.tree.TreeExpandListener.handle(TreeExpandListener.java:25)
	at com.couchbase.intellij.tree.CouchbaseWindowContent$3.treeExpanded(CouchbaseWindowContent.java:133)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2866)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3768)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2298)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.toggleExpandState(BasicTreeUI.java:2644)
	at com.intellij.ui.tree.ui.DefaultTreeUI.toggleExpandState(DefaultTreeUI.java:429)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.handleExpandControlClick(BasicTreeUI.java:2629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.checkForClickInExpandControl(BasicTreeUI.java:2577)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4090)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:4038)
	at com.intellij.util.ui.MouseEventAdapter.mousePressed(MouseEventAdapter.java:31)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:437)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4578)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: java.lang.Exception: The above exception was originally thrown by another thread at the following location.
		at com.couchbase.client.core.node.RoundRobinLocator.dispatch(RoundRobinLocator.java:119)
		at com.couchbase.client.core.Core.send(Core.java:398)
		at com.couchbase.client.core.Core.send(Core.java:371)
		at com.couchbase.client.core.classic.query.PreparedStatementStrategy.lambda$executeAdhoc$2(PreparedStatementStrategy.java:59)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
		at reactor.core.publisher.Mono.subscribeWith(Mono.java:4510)
		at reactor.core.publisher.Mono.toFuture(Mono.java:5019)
		at com.couchbase.client.core.classic.query.ClassicCoreQueryOps.queryAsync(ClassicCoreQueryOps.java:147)
		... 67 more
`
Steps to reproduce:
1. Setup a cluster with kv only (you can use that docker command and then set a kv only cluster)
`docker run --net=couchbase -d --name couchbase-server-kvonly -p 8091-8097:8091-8097 -p 9123:9123 -p 9140:9140 -p 9999:9999 -p 11206-11207:11206-11207 -p  11210:11210 -p 11280:11280 -p 18091-18095:18091-18095 -p 19102:19102 -p 10130:19130 -p 21150:21150 couchbase`
2. try to connect
3. As of 1.0.2 - The plugin works (pillowfight, export, import, cluster info, etc) but it doesn't enumerate docs and keep on throwing exceptions. 

Expected behavior:
1. Unavailable features should be disabled (like query, indexes, etc)
2. Documents should be able to be enumerated like in the Couchbase Web UI.

**Comment by deniswsrosa** [comment]
Done. waiting for release now.
